### ISSUE TITLE
Нарушение лицензии

### ISSUE THREAD

**Issue by Infactum** [lintest/AddinTemplate#2]
Код проекта содержит множественные заимствования из 
https://github.com/Infactum/addin-template, распространяемого по AGPL. Таким образом применять MIT лицензию к текущему коду нельзя.

**Comment by lintest** [comment]
Прошу прокомментировать какие участки кода Вы считаете своим ноу-хау, чтобы в будущем избежать проблем с лицензией.

Текст лицензии временно удалён.

**Comment by Infactum** [comment]
Ноу-хау это больше про патенты.  
Код в данном случае может являться достаточно тривиальным, но даже беглый просмотр показывает на факт копирования, а не написания с нуля в рамках той же идеи. А этого факта достаточно для требования применения именно AGPL.
Не указываю конкретные фрагменты сознательно. Просто хотел бы получить прямой ответ от Вас, имело ли копирование место быть.

**Comment by lintest** [comment]
Программный код писался полностью с нуля и существенно отличается от Вашего решения тем, что использует обёртку VariantHelper для типа tVariant, а также альтернативную реализацию обработчиков функций и процедур компоненты без использования шаблонов. Публичные имена методов для регистрации компоненты совпадают, но реализация отличается. 

Можно посчитать заимствованием только программный код для конвертации строк, хотя он достаточно универсальный. 

Прошу пометить участки кода, которые мешают применению лицензии MIT и я удалю из шаблона эти фрагменты.

**Comment by lintest** [comment]
Обратите внимание на существенное отличие, что моя реализация VariantHelper хранит в себе ссылку на tVariant и конвертация значений производится "на лету", Такое решение уже использовалось в моих предыдущих проектах.

**Comment by lintest** [comment]
Отказ от использования шаблонов для определения процедур и функций в моей реализации компоненты накладывает существенные ограничения на формат лямбда выражений в методах **AddProperty**, **AddProcedure** и **AddFunction**, поскольку требует обязательного использования в параметрах типа **VariantHelper**. Однако это позволяет легко решить задачу возврата в 1С измененных значений параметров.

**Comment by Infactum** [comment]
Я не оспариваю факт существования отличий. Но это не относится к озвученной проблеме лицензирования.

Отмечать конкретные куски кода и тратить на это время не вижу смысла. Что это даст? Вы же уже публично написали, что ничего не заимствовали. А на нет и суда нет. В "спортлото" тоже писать не планирую.

Зато решить, как в действительности дело обстояло, и сделать выводы, каждый теперь может самостоятельно.

**Comment by lintest** [comment]
Спасибо! Задачу закрываю.
